openapi: 3.1.0
info:
  title: Core - API
  description: 'The entire API definition of the system module.

    (Generated on: Mar 1, 2024 at 14:34:00)'
  contact:
    name: Binary Birds
    url: https://binarybirds.com
    email: info@binarybirds.com
  version: 1.0.0
tags: []
servers:
- url: http://localhost:8080
  description: dev
- url: http://localhost:8081
  description: live
components:
  schemas:
    FeatherCoreUnsupportedMediaTypeError:
      type: object
      description: ''
      properties:
        key:
          $ref: '#/components/schemas/FeatherCoreUnsupportedMediaTypeErrorKey'
        message:
          $ref: '#/components/schemas/FeatherCoreErrorMessage'
      required:
      - key
      - message
    FeatherCoreUnsupportedMediaTypeErrorKey:
      type: string
      description: You can use this key for translation purposes.
      examples:
      - application/json
      - text/html
    FeatherCoreInternalServerErrorError:
      type: object
      description: ''
      properties:
        key:
          $ref: '#/components/schemas/FeatherCoreInternalServerErrorErrorKey'
        message:
          $ref: '#/components/schemas/FeatherCoreErrorMessage'
      required:
      - key
      - message
    FeatherCoreInternalServerErrorErrorKey:
      type: string
      description: The key of the related object.
      examples:
      - module.model
      - foo.bar
    FeatherCoreGoneError:
      type: object
      description: ''
      properties:
        key:
          $ref: '#/components/schemas/FeatherCoreGoneErrorKey'
        message:
          $ref: '#/components/schemas/FeatherCoreErrorMessage'
      required:
      - key
      - message
    FeatherCoreGoneErrorKey:
      type: string
      description: The system key of the related object.
      examples:
      - module.model
      - foo.bar
    FeatherCoreNotAcceptableError:
      type: object
      description: ''
      properties:
        key:
          $ref: '#/components/schemas/FeatherCoreNotAcceptableErrorKey'
        message:
          $ref: '#/components/schemas/FeatherCoreErrorMessage'
      required:
      - key
      - message
    FeatherCoreNotAcceptableErrorKey:
      type: string
      description: The system key of the related object.
      examples:
      - module.model
      - foo.bar
    FeatherCoreMethodNotAllowedError:
      type: object
      description: ''
      properties:
        key:
          $ref: '#/components/schemas/FeatherCoreMethodNotAllowedErrorKey'
        message:
          $ref: '#/components/schemas/FeatherCoreErrorMessage'
      required:
      - key
      - message
    FeatherCoreMethodNotAllowedErrorKey:
      type: string
      description: The system key of the related object.
      examples:
      - module.model
      - foo.bar
    FeatherCoreNotFoundError:
      type: object
      description: ''
      properties:
        key:
          $ref: '#/components/schemas/FeatherCoreNotFoundErrorKey'
        message:
          $ref: '#/components/schemas/FeatherCoreErrorMessage'
      required:
      - key
      - message
    FeatherCoreNotFoundErrorKey:
      type: string
      description: The system key of the related object.
      examples:
      - module.model
      - foo.bar
    FeatherCoreBadRequestError:
      type: object
      description: ''
      properties:
        key:
          $ref: '#/components/schemas/FeatherCoreBadRequestErrorKey'
        message:
          $ref: '#/components/schemas/FeatherCoreErrorMessage'
      required:
      - key
      - message
    FeatherCoreBadRequestErrorKey:
      type: string
      enum:
      - missingRequestBody
      - invalidRequestBody
      description: You can use this key for translation purposes.
      examples:
      - missingRequestBody
      - invalidRequestBody
    FeatherCoreUnprocessableContentError:
      type: object
      description: ''
      properties:
        key:
          $ref: '#/components/schemas/FeatherCoreUnprocessableContentErrorKey'
        message:
          $ref: '#/components/schemas/FeatherCoreErrorMessage'
        failures:
          $ref: '#/components/schemas/FeatherCoreUnprocessableContentErrorFailure'
      required:
      - key
      - message
      - failures
    FeatherCoreUnprocessableContentErrorKey:
      type: string
      const: validation
      description: You can use this key for translation purposes.
      examples:
      - validation
    FeatherCoreUnprocessableContentErrorFailure:
      type: array
      description: ''
      items:
        $ref: '#/components/schemas/FeatherCoreUnprocessableContentErrorFailureDetail'
      maxItems: 1000
      minItems: 0
    FeatherCoreUnprocessableContentErrorFailureDetail:
      type: object
      description: ''
      properties:
        key:
          $ref: '#/components/schemas/FeatherCoreUnprocessableContentErrorFailureDetailKey'
        message:
          $ref: '#/components/schemas/FeatherCoreErrorMessage'
      required:
      - key
      - message
    FeatherCoreUnprocessableContentErrorFailureDetailKey:
      type: string
      description: Related field key for the error detail.
      examples:
      - email
      - password
      - coordinate
      - coordinate.latitude
      - coordinate.longitude
    FeatherCoreUnauthorizedError:
      type: object
      description: ''
      properties:
        key:
          $ref: '#/components/schemas/FeatherCoreUnauthorizedErrorKey'
        message:
          $ref: '#/components/schemas/FeatherCoreErrorMessage'
      required:
      - key
      - message
    FeatherCoreUnauthorizedErrorKey:
      type: string
      const: invalidUserToken
      description: You can use this key for translation purposes.
      examples:
      - invalidUserToken
    FeatherCoreConflictError:
      type: object
      description: ''
      properties:
        key:
          $ref: '#/components/schemas/FeatherCoreConflictErrorKey'
        message:
          $ref: '#/components/schemas/FeatherCoreErrorMessage'
      required:
      - key
      - message
    FeatherCoreConflictErrorKey:
      type: string
      description: The system key of the related object.
      examples:
      - module.model
      - foo.bar
    FeatherCoreForbiddenError:
      type: object
      description: ''
      properties:
        key:
          $ref: '#/components/schemas/FeatherCoreForbiddenErrorKey'
        message:
          $ref: '#/components/schemas/FeatherCoreErrorMessage'
      required:
      - key
      - message
    FeatherCoreForbiddenErrorKey:
      type: string
      description: The system key of the related object.
      examples:
      - module.model
      - foo.bar
    FeatherCoreErrorMessage:
      type: string
      description: The original error message provided by the system.
      examples:
      - Something went wrong with the request.
    FeatherCoreHeadersContentLength:
      type: integer
      description: Content length
    FeatherCoreListCount:
      type: integer
      description: Total elements
      examples:
      - 42
    FeatherCoreListPage:
      type: object
      description: Page properties
      properties:
        size:
          $ref: '#/components/schemas/FeatherCoreListPageSize'
        index:
          $ref: '#/components/schemas/FeatherCoreListPageIndex'
      required:
      - size
      - index
    FeatherCoreListPageSize:
      type: integer
      default: 50
      description: Page size
      examples:
      - 10
    FeatherCoreListPageIndex:
      type: integer
      default: 0
      description: Page index
      examples:
      - 0
    FeatherCoreListOrder:
      type: string
      enum:
      - asc
      - desc
      default: asc
      description: Order of the list (ascending or descending).
      examples:
      - asc
      - desc
    FeatherCoreListSearch:
      type: string
      description: Value of the search term.
      examples:
      - foo
    FeatherCoreCreatedAt:
      type: string
      format: date-time
      description: Object creation date
      examples:
      - '2023-02-10 09:20:15'
    FeatherCoreUpdatedAt:
      type: string
      format: date-time
      description: Last update for the object
      examples:
      - '2023-02-10 09:20:15'
  responses:
    FeatherCoreUnsupportedMediaType:
      description: Unsupported media type
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/FeatherCoreUnsupportedMediaTypeError'
    FeatherCoreHead:
      description: Ok
      headers:
        Content-Length:
          $ref: '#/components/headers/Content-Length'
    FeatherCoreNoContent:
      description: No content
    FeatherCoreInternalServerError:
      description: InternalServerError
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/FeatherCoreInternalServerErrorError'
    FeatherCoreOk:
      description: ok
    FeatherCoreGone:
      description: Gone
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/FeatherCoreGoneError'
    FeatherCoreNotAcceptable:
      description: Not acceptable
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/FeatherCoreNotAcceptableError'
    FeatherCoreMethodNotAllowed:
      description: Method not allowed
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/FeatherCoreMethodNotAllowedError'
    FeatherCoreNotFound:
      description: Not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/FeatherCoreNotFoundError'
    FeatherCoreBadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/FeatherCoreBadRequestError'
    FeatherCoreUnprocessableContent:
      description: Unprocessable content
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/FeatherCoreUnprocessableContentError'
    FeatherCoreUnauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/FeatherCoreUnauthorizedError'
    FeatherCoreConflict:
      description: Conflict
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/FeatherCoreConflictError'
    FeatherCoreForbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/FeatherCoreForbiddenError'
  parameters:
    FeatherCoreListSearch:
      name: search
      in: query
      schema:
        $ref: '#/components/schemas/FeatherCoreListSearch'
      description: The list search value
    FeatherCoreListPageSize:
      name: pageSize
      in: query
      schema:
        $ref: '#/components/schemas/FeatherCoreListPageSize'
      description: The number of items per page
    FeatherCoreListPageIndex:
      name: pageIndex
      in: query
      schema:
        $ref: '#/components/schemas/FeatherCoreListPageIndex'
      description: The current page number
    FeatherCoreListOrder:
      name: order
      in: query
      schema:
        $ref: '#/components/schemas/FeatherCoreListOrder'
      description: Sort order parameter
  headers:
    Content-Length:
      schema:
        $ref: '#/components/schemas/FeatherCoreHeadersContentLength'
      description: Content length header
  securitySchemes:
    FeatherCoreBearerToken:
      description: Authorization header using a Bearer token
      type: http
      scheme: bearer
      bearerFormat: token
